server.port: 8031

spring:
  datasource:
    url: jdbc:h2:mem:camunda-h2-database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2.console:
    enabled: true
    path: /h2-console
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          cp4na:
            provider: cp4na
            client-id: LmClient
            client-secret: pass123
            authorization-grant-type: client_credentials
        provider:
          cp4na:
            token-uri: https://ib-orc-230-ishtar-001:8280/oauth/token
            
  jackson.serialization.FAIL_ON_EMPTY_BEANS: false

zeebe:
  client:
    broker:
      gateway-address: 127.0.0.1:26500
    security:
      plaintext: true


logging.level:
  root: INFO